sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t esahakian/docker-react .
    #- docker build -t esahakian/docker-react -f Dockerfile.dev .

#script:
#    - docker run -e CI=true esahakian/docker-react npm run test

deploy:
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    edge: true
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'docker-react'
    env: 'DockerReact-env'
    bucket_name: 'elasticbeanstalk-us-east-2-612756466101'
    bucket_path: 'docker-react'
    on:
        branch: master
